[package]
name = "syslog-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20.6"
webpki-roots = "0.22.4"
webpki = "0.22.0"
