name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    # We use 20.04 so we build with glibc 2.31 to support debian bullseye
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      if: success() || failure()
      run: cargo build --verbose --release
    - name: Save build artifact
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: syslog-wrapper
        path: target/release/syslog-wrapper
